In [ ]:
#Author: Juliana Shihadeh 
#Pattern Recognition and Data Mining
#Actual Testing 

In [1]:
#Defining the Logistic Regression Ensemble Model
from sklearn.linear_model import LogisticRegression
def LogisticRegressionEnsemble(X_train, y_train):
    models = []
    for i in range(0, 27):
        modelname = 'LRModel' + str(i)
        #Add code above in here

        #Change the last two lines so they save to separate models
        logreg = LogisticRegression(solver='lbfgs', max_iter = 100000)
        test_labels = y_train[col_names[i]]
        modelname = logreg.fit(X_train, test_labels)

        #At the end, append to the list of models
        models.append(modelname)
    return models

In [2]:
#Defining the Random Forest Ensemble Model
from sklearn.ensemble import RandomForestClassifier
def RandomForestEnsemble(X_train, y_train):    
    #Train Random Forest Models on all columns
    models = []
    for i in range(0, 27):
        model = RandomForestClassifier(n_estimators=100, 
                                   bootstrap = True,
                                   max_features = 'sqrt')
        train_labels = y_train[col_names[i]]
        #train = All the features of our data
        #Fits the features to the labels
        model = model.fit(X_train, train_labels)
        models.append(model)
    return models

In [23]:
#Call Test on an Ensemble Model to test it's performance
from sklearn.datasets import make_classification
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import f1_score
def test_model(models, X_test, y_test):
    #Method 1: Predict results of all the tests, then loop through and print out all the results
    #Run each test through every Random Forest Model and append the result
    #Two separate loops
    #O(n): 32 + numRecords (test cases)
    all_predictions = []
    all_accuracies = []
    all_f1scores = []
    for i in range(0, 27):
        #Select the model
        #modelname = 'model' + str(i)
        #Test the model. Pass all the test data, not one by one returns labels of all the test data
        predictions = models[i].predict(X_test)
        #Final shape should be 32 X 82717: 32 lists of 82717 length 
        test_labels = y_test[col_names[i]]
        print("The number of values in a test_label:")
        print(len(test_labels))
        a = metrics.accuracy_score(test_labels, predictions)
        print("Accuracy:",a)
        print(classification_report(test_labels, predictions))
        f1 = f1_score(test_labels, predictions, average='weighted')
        all_f1scores.append(f1)
        all_accuracies.append(a)
        all_predictions.append(predictions)
    #print("Length of all_f1scores and all_accuracies:")
    #print(len(all_f1scores))
    #print(len(all_accuracies))
    len(all_f1scores)
    s = 0.0
    #Compute the overall f1-score of the model by taking the average of all the f1-scores of the random forests
    for i in all_f1scores:
        s = s + i
    final_acc = s / len(all_f1scores)
    print(final_acc)
    print("all_predictions LIST")
    print(all_predictions)
    return list(all_predictions)

In [47]:
#Author: Juliana 
#All Post Processing Steps

#What post processing steps copmleted are:
#1. Converts classifications of 1 and 0s to the corresponding classes
#2. Matches all players that can substitue a position
#3. Recommends the top 3 players based on player's overall score



#Pass in the player position and the predictions list
def matchingplayers(player_position, predictions, test_data, modelname):
    #Create a dictionary of all the player_positions and what they stand for
    positions = {"cb": 'Centre back',
                "cdm": 'Central defensive midfielder',
                "cf": 'Center forward',
                "cm": 'Centre midfielder',
                "gk": 'Goalkeeper',
                "lb": 'Left back',
                "lm": 'Left midfielder',
                "lw": 'Left winger',
                "rb": 'Right back',
                "rm": 'Right midfielder',
                "rw": 'Right winger',
                "st": 'Striker',
                "cb": 'Center-back',
                "lcb": 'Left center-back',
                "rcb": 'Right center-back',
                "lb": 'Left-back',
                "rb": 'Right-back',
                "cm": 'Centre midfield',
                "ldm": 'Left defense midfielder',
                "lam": 'Left attacking midfield',
                "rdm": 'Right defense midfield',
                "ram": 'Right attacking midfield',
                "cdm": 'Centre defensive midfield',
                "cam": 'Centre attacking midfield',
                "lm" : 'Left midfield',
                "rm" : 'Right midfield',
                "st": 'Striker',
                "cf": 'Center forward',
                "lw": 'Left winger',
                "rw": 'Right winger', 
                "ls": 'Left striking',
                "rs": 'Right striking', 
                "lf": 'Left forward', 
                "rf": 'Right forward',
                "lcm": 'Left center midfielder',
                "rcm": 'Right center midfielder',
                "lwb": 'Left wing back',
                "rwb": 'Rigth wing back'}
    #Lists
    #cm = ["cm", "ldm", "lam", "rdm", "ram", "cdm", "cam", "lm" , "rm"]
    #attack = ["sf", "cf", "lw", "rw" , "ls", "rs"]
    #defense = ["defense", "cb", "lcb", "rcb", "lb", "rb"]   
    #lb = ["cb", "cdm","cf", "cm", "lb", "lm", "lw", "rb", "rm", "rw", "st"]
    #gk = ['gk']
    attack=["ls","st","rs","lw","lf","cf","rf","rw"]
    midfield=["lam","cam","ram","lm","lcm","cm","rcm","rm","ldm","cdm","rdm"]
    defense=["lwb","rwb","lb","lcb","cb","rcb","rb"]
    gk=["gk"]
    
    matches = []
    position_name = positions.get(player_position) 
    file_name = (modelname + "_Positions_A_Player_Can_Substitute_For_" + position_name + ".txt")
    outputFile = open(file_name,'w')
    for i in range(len(predictions)):
        for j in range(len(predictions[i])):
            if predictions[i][j] == player_position:
                #Look up the player's name from the original pandas data frame
                player_name = test_data.loc[i, 'long_name']
                #print("The player's name:")
                #print(player_name)
                #position_name = positions.get(player_position) 
                #print("The position name:")
                #print(position_name)
                if player_position in defense:
                    type_position = "defense"
                elif player_position in attack:
                    type_position = "attacker"
                elif player_position in midfield:
                    type_position = "midfield"
                elif player_position in gk:
                    type_position = 'goal keeper'
                print(player_name + " can substitute for the position " + player_position + ", " + position_name + " position, which is a(n) " + type_position + " position. \n")
                outputFile.writelines(player_name + " can substitute for the position " + player_position + ", " + position_name + " position, which is a(n) " + type_position + " position. \n")
                #player = player_name[i] 
                matches.append(player_name)
    topthreeplayers(len(predictions), test_data, matches, position_name, modelname)

#Pass the predictions list and the dataframe of the test data
def topthreeplayers(total_predictions, df, matches, position, modelname):  
        overall_scores_dictionary = {}
        for i in matches:
            #print("In MATCHES LOOP")
            #print(i)
            r = df.loc[df['long_name'] == i]
            #print(r)
            ind = r.index
            t = df.get_value( ind , 3 , takeable = True) 
            overall_score = t[0]
            #print("The overall score of the player")
            #print(overall_score)

    
            #print("The index is:")
            #print(i)
            overall_scores_dictionary[i] = overall_score
            
        #Sort dictionary by value
        #from collections import OrderedDict
        #sorted_scores = OrderedDict(sorted(overall_scores_dictionary.items(), key=lambda x: x[1]))
        sorted_scores = sorted(overall_scores_dictionary.items() ,  key=lambda x: x[1])
        
        print('\n')
        file_name = (modelname + "_" + position + "_Roster.txt")
        outputFile = open(file_name,'w')
        print("The entire roster of players who can be swapped for the " + '\033[1m' + position + '\033[0m' + " position in order of best overall performance to least based on the " + modelname + "are:")
        roster = []
        outputFile.writelines("The entire roster of players who can be swapped for the "+ position + " position in order of best overall performance to least based on the " + modelname + " are: \n")
        #for i in sorted_scores:
        for i in range(len(sorted_scores)-1, -1, -1):
            roster.append(sorted_scores[i][0])
            #roster.append(i[0])
            outputFile.writelines(sorted_scores[i][0])
            outputFile.writelines('\n')
            print(sorted_scores[i][0])
        outputFile.close()
        
        
        l = len(sorted_scores)
        #ids of top 3
        print("The 3 Players with the highest overall performance score from all players who can be a subtitue for the " + '\033[1m' + position + '\033[0m' + " position are: " )
        id_top_1 = sorted_scores[l-1][0]
        print("1. " + '\033[1m' + id_top_1 + '\033[0m' + " with an overall score: " + '\033[1m' + str(sorted_scores[l-1][1]) + '\033[0m')
        id_top_2 = sorted_scores[l-2][0]
        print("2. " + '\033[1m' + id_top_2 + '\033[0m' + " with an overall score: " + '\033[1m' + str(sorted_scores[l-2][1]) + '\033[0m')
        id_top_3 = sorted_scores[l-3][0]
        print("3. " + '\033[1m' + id_top_3 + '\033[0m' + " with an overall score: " + '\033[1m' + str(sorted_scores[l-3][1]) + '\033[0m')
        
        #print(roster)
           
        #Looks up the specifics names of the players
        #name_top_1 = df.loc[id_top_1, 'long_name']
        #name_top_2 = df.loc[id_top_2, 'long_name']
        #name_top_3 = df.loc[id_top_3, 'long_name']
        
        #Creates a data frame of the final resultls
        #row_labels = [id_top_1, id_top_2, id_top_3]
        #col_labels = ['long_name']
        #final_results = df.lookup(self, row_labels, col_labels)
        #print("The top 3 recommended players are: \n1. " + id_top_1 + "\n2. " + id_top_2 + "\n3. " + id_top_3 + "\n")

#Pass the final data frame that holds all the class informatiion
def apply_postprocessing(pred_df, modelname, position):
    #Following line of code based off of Apeksha's Code From Feature Extraction
    #print("Apply null drop")
    #print("The pred_df:")
    #print(pred_df)
    labels=pred_df[pred_df.apply(lambda x: x == pred_df.max(axis = 1))] 
    #print(labels)
    classes=[]
    #print("Labels dataframe")
    #print(labels)
    #Write all labels to file named model
    file_name = modelname + position + '.txt'
    outputFile = open(file_name,'w')

    #print("At the start of the for loop")
    #print("Label shape:")
    #print(labels.shape[0])
    for i in range(labels.shape[0]):
        #Following line of code based off of Apeksha's Code From Feature Extraction
        l=list(labels.columns[np.isfinite(labels.iloc[i])])
        #print(l)
        formatted_l=map(lambda x:x+' ', l)
        #Eventually add in the players's name too
        outputFile.writelines("ID: " + str(i) + ", Total Classes: " + str(len(l)) + " Classes: ")
        outputFile.writelines(formatted_l)
        outputFile.writelines('\n')
        #for i in l:
        #    outputFile.write(i)
        #    outputFile.write('\n')
        classes.append(l)
        #Save the classes to a file
    print("Number of classes:")
    print(len(classes))
    #print(classes)
    outputFile.close()
    
    #Import the dataframe of test data
    #Getting the test data
    import pandas as pd
    #Change the file name here
    #test_data = pd.read_csv('/Users/julianashihadeh/Desktop/GroupProject/Player_Position_Prediction/MondayVersion/Player_Position_Prediction/names.csv', sep=",",header="infer")
    training_data = pd.read_csv('data/names.csv', sep=",",header="infer", low_memory=False)
    print("TEST DATA READ")
    #print(test_data.head())

    predictions = classes    
    number_of_predictions = len(classes)
    #Pass a player position
    #Match all players that can substitute a position
    matchingplayers(position, predictions, test_data, modelname)
    #List top 3 players that can substitue a position
    #topthreeplayers(number_of_predictions, test_data)

In [5]:
#The Full Train set and actual Test Set to run on the model
#Extract all the training/testing data and training/test labels and the column names
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

#Extracting all the train labels
#training_labels = pd.read_csv('/Users/julianashihadeh/Desktop/GroupProject/Player_Position_Prediction/SundayVersion/Player_Position_Prediction/train_labels.csv', sep=",",header="infer", low_memory = False)         
training_data = pd.read_csv('data/train_labels.csv', sep=",",header="infer", low_memory=False)
print(training_labels.head())

#Extracting all the training data
import pandas as pd
import numpy as np
#training_data = pd.read_csv('/Users/julianashihadeh/Desktop/GroupProject/Player_Position_Prediction/SundayVersion/Player_Position_Prediction/train1.csv', sep=",",header="infer", low_memory=False)
training_data = pd.read_csv('data/train1.csv', sep=",",header="infer", low_memory=False)
print(training_data.head())

#Getting the test data
#test_data = pd.read_csv('/Users/julianashihadeh/Desktop/GroupProject/Player_Position_Prediction/SundayVersion/Player_Position_Prediction/test.csv', sep=",",header="infer")
training_data = pd.read_csv('data/test.csv', sep=",",header="infer", low_memory=False)
print(test_data.head())

#Getting the test labels
#test_labels = pd.read_csv('/Users/julianashihadeh/Desktop/GroupProject/Player_Position_Prediction/SundayVersion/Player_Position_Prediction/test_label.csv', sep=",",header="infer")
training_data = pd.read_csv('data/test_labels.csv', sep=",",header="infer", low_memory=False)
print(test_labels.head())

X_train = training_data
y_train = training_labels
X_test = test_data
y_test = test_labels
                                                   
#print(y_train)                                                    
col_names = y_train.columns.values.tolist()
#print(col_names)
#print(len(col_names))

#for i in range(len(col_names)):
#    train_labels = y_train[col_names[i]]
    #print(train_labels)
#    print(len(train_labels))


   gk_positioning  ls  st  rs  lw  lf  cf  rf  rw  lam  ...  lwb  ldm  cdm  \
0               0   0   0   0   1   0   0   0   1    1  ...    0    0    0   
1               0   1   1   1   0   1   1   1   0    0  ...    0    0    0   
2               0   0   0   0   1   0   0   0   1    1  ...    0    0    0   
3               0   1   1   1   0   0   0   0   0    0  ...    0    0    0   
4               1   0   0   0   0   0   0   0   0    0  ...    0    0    0   

   rdm  rwb  lb  lcb  cb  rcb  rb  
0    0    0   0    0   0    0   0  
1    0    0   0    0   0    0   0  
2    0    0   0    0   0    0   0  
3    0    0   0    0   0    0   0  
4    0    0   0    0   0    0   0  

[5 rows x 27 columns]
   attacking_crossing  attacking_finishing  attacking_heading_accuracy  \
0                  84                   91                          71   
1                  83                   98                          86   
2                  80                   87                          50

In [6]:
#Train Random Forest Ensemble
RF_models = RandomForestEnsemble(X_train, y_train)
print("Number of Random Forest models in the ensemble should be 27. Verification:")
print(len(RF_models))

Number of Random Forest models in the ensemble should be 27. Verification:
27


In [ ]:
#Train LogisticRegressionEnsemble
LRE_models = LogisticRegressionEnsemble(X_train, y_train)
print("Number of Logist Regression models in the ensemble should be 27. Verification:")
print(len(LRE_models))

In [24]:
#Start of Random Forest Ensemble Test and Post Processing 
from sklearn.datasets import make_classification
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import f1_score
all_predictions = test_model(RF_models, X_test, y_test)    

The number of values in a test_label:
18278
Accuracy: 1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     16242
           1       1.00      1.00      1.00      2036

   micro avg       1.00      1.00      1.00     18278
   macro avg       1.00      1.00      1.00     18278
weighted avg       1.00      1.00      1.00     18278

The number of values in a test_label:
18278
Accuracy: 0.982054929423
              precision    recall  f1-score   support

           0       0.99      0.99      0.99     15791
           1       0.95      0.92      0.93      2487

   micro avg       0.98      0.98      0.98     18278
   macro avg       0.97      0.96      0.96     18278
weighted avg       0.98      0.98      0.98     18278

The number of values in a test_label:
18278
Accuracy: 0.981836087099
              precision    recall  f1-score   support

           0       0.99      0.99      0.99     15791
           1       0.95      0.91      0.

The number of values in a test_label:
18278
Accuracy: 0.957927563191
              precision    recall  f1-score   support

           0       0.97      0.99      0.98     15770
           1       0.89      0.79      0.84      2508

   micro avg       0.96      0.96      0.96     18278
   macro avg       0.93      0.89      0.91     18278
weighted avg       0.96      0.96      0.96     18278

The number of values in a test_label:
18278
Accuracy: 0.952730057993
              precision    recall  f1-score   support

           0       0.96      0.98      0.97     16263
           1       0.84      0.71      0.77      2015

   micro avg       0.95      0.95      0.95     18278
   macro avg       0.90      0.84      0.87     18278
weighted avg       0.95      0.95      0.95     18278

The number of values in a test_label:
18278
Accuracy: 0.968431994748
              precision    recall  f1-score   support

           0       0.97      0.99      0.98     13788
           1       0.96      0

In [26]:
#To create a dataframe from the predictions
print(all_predictions)
df = pd.DataFrame(all_predictions, index = ['gk', 'ls', 'st', 'rs', 'lw', 'lf', 'cf', 'rf', 'rw', 'lam', 'cam', 'ram', 'lm', 'lcm', 'cm', 'rcm', 'rm', 'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb'])
addT = df.T

[array([0, 0, 0, ..., 0, 0, 0]), array([0, 1, 0, ..., 0, 0, 0]), array([0, 1, 0, ..., 0, 0, 0]), array([0, 1, 0, ..., 0, 0, 0]), array([0, 0, 1, ..., 0, 0, 0]), array([1, 1, 1, ..., 0, 0, 0]), array([1, 1, 0, ..., 0, 0, 0]), array([1, 1, 1, ..., 0, 0, 0]), array([0, 0, 1, ..., 0, 0, 0]), array([1, 0, 1, ..., 0, 0, 0]), array([1, 0, 1, ..., 0, 0, 0]), array([1, 0, 1, ..., 0, 0, 0]), array([0, 0, 0, ..., 0, 0, 0]), array([0, 0, 0, ..., 0, 0, 0]), array([0, 0, 0, ..., 0, 0, 0]), array([0, 0, 0, ..., 0, 0, 0]), array([0, 0, 0, ..., 0, 0, 0]), array([0, 0, 0, ..., 0, 0, 0]), array([0, 0, 0, ..., 0, 0, 0]), array([0, 0, 0, ..., 0, 1, 1]), array([0, 0, 0, ..., 0, 1, 1]), array([0, 0, 0, ..., 0, 0, 0]), array([0, 0, 0, ..., 0, 0, 0]), array([0, 0, 0, ..., 1, 1, 1]), array([0, 0, 0, ..., 1, 1, 1]), array([0, 0, 0, ..., 1, 1, 1]), array([0, 0, 0, ..., 0, 0, 0])]


In [27]:
print(addT.head())
print(all_predictions)

   gk  ls  st  rs  lw  lf  cf  rf  rw  lam  ...  lwb  ldm  cdm  rdm  rwb  lb  \
0   0   0   0   0   0   1   1   1   0    1  ...    0    0    0    0    0   0   
1   0   1   1   1   0   1   1   1   0    0  ...    0    0    0    0    0   0   
2   0   0   0   0   1   1   0   1   1    1  ...    0    0    0    0    0   0   
3   1   0   0   0   0   0   0   0   0    0  ...    0    0    0    0    0   0   
4   0   0   0   0   1   0   0   0   1    1  ...    0    0    0    0    0   0   

   lcb  cb  rcb  rb  
0    0   0    0   0  
1    0   0    0   0  
2    0   0    0   0  
3    0   0    0   0  
4    0   0    0   0  

[5 rows x 27 columns]
[array([0, 0, 0, ..., 0, 0, 0]), array([0, 1, 0, ..., 0, 0, 0]), array([0, 1, 0, ..., 0, 0, 0]), array([0, 1, 0, ..., 0, 0, 0]), array([0, 0, 1, ..., 0, 0, 0]), array([1, 1, 1, ..., 0, 0, 0]), array([1, 1, 0, ..., 0, 0, 0]), array([1, 1, 1, ..., 0, 0, 0]), array([0, 0, 1, ..., 0, 0, 0]), array([1, 0, 1, ..., 0, 0, 0]), array([1, 0, 1, ..., 0, 0, 0]), array([1, 0

In [41]:
#Post Processing
#Pass the final Data Frame of labels, the model name, and the position 
#Positions you can pick from to classify what players can substitue for that position
#p = ['gk', 'ls', 'st', 'rs', 'lw', 'lf', 'cf', 'rf', 'rw', 'lam', 'cam', 'ram', 'lm', 'lcm', 'cm', 'rcm', 'rm', 'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb']
apply_postprocessing(addT, "RandomForestEnsemble", 'rw')

Number of classes:
18278
TEST DATA READ
Neymar da Silva Santos Junior can substitute for the position rw, Right winger position, which is a(n) attacker position. 

Eden Hazard can substitute for the position rw, Right winger position, which is a(n) attacker position. 

Mohamed  Salah Ghaly can substitute for the position rw, Right winger position, which is a(n) attacker position. 

Kylian Mbappé can substitute for the position rw, Right winger position, which is a(n) attacker position. 

Antoine Griezmann can substitute for the position rw, Right winger position, which is a(n) attacker position. 

Paulo Bruno Exequiel Dybala can substitute for the position rw, Right winger position, which is a(n) attacker position. 

Raheem Sterling can substitute for the position rw, Right winger position, which is a(n) attacker position. 

Marco Reus can substitute for the position rw, Right winger position, which is a(n) attacker position. 

Sadio Mané can substitute for the position rw, Right winge


Aylton Filipe Boa Morte can substitute for the position rw, Right winger position, which is a(n) attacker position. 

Dominik Frieser can substitute for the position rw, Right winger position, which is a(n) attacker position. 

Richard Boateng can substitute for the position rw, Right winger position, which is a(n) attacker position. 

Mamadou Koné can substitute for the position rw, Right winger position, which is a(n) attacker position. 

Modou Barrow can substitute for the position rw, Right winger position, which is a(n) attacker position. 

Joseph-Claude Gyau can substitute for the position rw, Right winger position, which is a(n) attacker position. 

Javier Osvaldo Mendoza can substitute for the position rw, Right winger position, which is a(n) attacker position. 

Julien  Bègue can substitute for the position rw, Right winger position, which is a(n) attacker position. 

Patrick Twumasi can substitute for the position rw, Right winger position, which is a(n) attacker position. 



Emmanuel Jorge Ledesma can substitute for the position rw, Right winger position, which is a(n) attacker position. 

Paul Taylor can substitute for the position rw, Right winger position, which is a(n) attacker position. 

Mirko Eramo can substitute for the position rw, Right winger position, which is a(n) attacker position. 

Temitope Obadeyi can substitute for the position rw, Right winger position, which is a(n) attacker position. 

Dominik Hofbauer can substitute for the position rw, Right winger position, which is a(n) attacker position. 

Daniel Powell can substitute for the position rw, Right winger position, which is a(n) attacker position. 

임상협 廉桑 can substitute for the position rw, Right winger position, which is a(n) attacker position. 

Ben Reeves can substitute for the position rw, Right winger position, which is a(n) attacker position. 

Manuel Schwenk can substitute for the position rw, Right winger position, which is a(n) attacker position. 

Marco Aratore can substit

Kevin Perez can substitute for the position rw, Right winger position, which is a(n) attacker position. 

Nathan Ferguson can substitute for the position rw, Right winger position, which is a(n) attacker position. 

Mohammad Fuad Al Thani can substitute for the position rw, Right winger position, which is a(n) attacker position. 

Florian Gonzales can substitute for the position rw, Right winger position, which is a(n) attacker position. 

William Longbottom can substitute for the position rw, Right winger position, which is a(n) attacker position. 

Ellis Iandolo can substitute for the position rw, Right winger position, which is a(n) attacker position. 

高天意 can substitute for the position rw, Right winger position, which is a(n) attacker position. 

西本 雅崇 can substitute for the position rw, Right winger position, which is a(n) attacker position. 

赵英杰 can substitute for the position rw, Right winger position, which is a(n) attacker position. 

Bryan Mendoza can substitute for the po

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ipykernel_launcher.py:100: FutureWarning: get_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead




The entire roster of players who can be swapped for the Right winger position in order of best overall performance to least based on the RandomForestEnsembleare:
Neymar da Silva Santos Junior
Eden Hazard
Mohamed  Salah Ghaly
Kylian Mbappé
Antoine Griezmann
Sadio Mané
Raheem Sterling
Paulo Bruno Exequiel Dybala
Marco Reus
Lorenzo Insigne
Dries Mertens
Bernardo Mota Veiga de Carvalho e Silva
Ángel Fabián Di María Hernández
Leroy Sané
Philippe Coutinho Correia
Gareth Frank Bale
Hakim Ziyech
Alejandro Darío Gómez
Iago Aspas Juncal
Riyad Mahrez
Jadon Sancho
Kai Havertz
Nabil Fekir
José María Callejón Bueno
Ivan Perišić
Serge Gnabry
Ousmane Dembélé
Felipe  Anderson Pereira Gomes
Julian Brandt
Kingsley Coman
Memphis Depay
Douglas Costa de Souza
Edin Višća
Gonçalo Manuel Ganchinho Guedes
Anthony Martial
Florian Thauvin
Marco Asensio Willemsen
Marcus Rashford
Yannick Ferreira Carrasco
Lucas Rodrigues M. Silva
Carlos Alberto Vela Garrido
Thomas Lemar
Julian Draxler
Wilfried Zaha
Ronaldo Jailso

Neyder Stiven Moreno Betancur
Flavio Jesús Santos Carrillo
Joshua Harrop
Gabriel Teodoro Martinelli Silva
Martín Merquelanz
Yanis Merdji
Lautaro Comas
Todor Nedelev
Farid El Melali
Jorgino Kaio Baumer Negrão
Athanasios Androutsos
Noah Okafor
Ubong Ekpai
Marvin Stefaniak
Erich  Berko
Emmanuel Sabbi
Carlos Uriel Antuna Romero
Nabil Bahoui
Tiago Alves Sales de Lima
Dani de Wit
Ferris N'Goma
仲川 輝人
Kazenga LuaLua
Sebastian Maier
Álvaro Cejudo Carmona
Jann George
Julian Green
Uffe Manich Bech
Moritz Stoppelkamp
Sead Hakšabanovič
Diego Steven Gómez Maldonado
Maximiliano Comba
Stefano  Beltrame
Giorgi Papunashvili
Gilbert Koomson
Elvis Manu
Juan Mejídez
Bautista Merlini
Jairo Izquierdo González
Keanu Staude
Stefan Aigner
Thorsten  Röcher
Hildeberto José Morgado Pereira
한교원 韩教元
Eric Larsson
Mariano Omar Barbieri
Andrew Nabbout
Alberto Cayarga Fernández
Edgar Salli
Hernán Darío Burbano
José Antonio Ferrández Pomares
Ikechi Anya
Wilfried Kanga
Juan Hernández García
Pablo Martínez
Thomas Touré
伊藤 

Jamie McGrath
Mattias Moström
Nando Nöstlinger
Adrien Lebeau
Wes McDonald
Erdoğan Yeşilyurt
Shane McLoughlin
Ayman Al Khulaif
Scott Burgess
Christian Conteh
Dillon Serna
David Vržogić
Michael Olise
George Kweku Davies
Evans Mensah
Ateef Konaté
Sirlord Conteh
Edwin Cerna
Nathan Broadhead
Raphael Obermair
Armand Laurienté
Iván Marcelo Rozas Agüero
雷永驰
Johannes Bühler
Nils Blumberg
Thibaud Verlinden
Marc  Rochester Sørensen
刘洋
Din Sula
Dzenis Kozica
Hamza Masoudi
이승모 Seung Mo Lee
Gianluca Gaetano
Emanuele Cicerelli
Robert Moldoveanu
Michee Ngalina
Víctor Ruiz Abril
Arnold Budimbu
Moutir Chajia
DeJuan Jones
Jairo Torres
Julian Guttau
Giles Coke
Yohan Brun
Mathieu Choinière
Benjamin Goller
Paulo Victor da Silva
Josh Barrett
Layton Ndukwu
Babacar Dione
Tyron Ivanof
Hernan Luna
Jeppe Friborg Simonsen
Harry Trewbridge
有馬 幸太郎
Antonio López
Gabriel Tadeu Strefezza Rebecato
Bobby Adekanye
Ali Hassan Al Asmari
Alejandro Zendejas Saavedra
Bartosz Bida
刘若钒
Alessio Tribuzzi
Benedict dos Santos
Max Kr

In [43]:
#Train LogisticRegressionEnsemble
LRE_models = LogisticRegressionEnsemble(X_train, y_train)
print("Number of Logistic Regression models in the ensemble should be 27. Verification:")
print(len(LRE_models))

Number of Logistic Regression models in the ensemble should be 27. Verification:
27


In [44]:
#Start of LogisticRegression Ensemble Test and Post Processing
from sklearn.datasets import make_classification
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import f1_score
test_model(LRE_models, X_test, y_test) 

The number of values in a test_label:
18278
Accuracy: 1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     16242
           1       1.00      1.00      1.00      2036

   micro avg       1.00      1.00      1.00     18278
   macro avg       1.00      1.00      1.00     18278
weighted avg       1.00      1.00      1.00     18278

The number of values in a test_label:
18278
Accuracy: 0.983039719882
              precision    recall  f1-score   support

           0       0.99      0.99      0.99     15791
           1       0.96      0.92      0.94      2487

   micro avg       0.98      0.98      0.98     18278
   macro avg       0.97      0.96      0.96     18278
weighted avg       0.98      0.98      0.98     18278

The number of values in a test_label:
18278
Accuracy: 0.983039719882
              precision    recall  f1-score   support

           0       0.99      0.99      0.99     15791
           1       0.96      0.92      0.

              precision    recall  f1-score   support

           0       0.97      0.98      0.98     13788
           1       0.95      0.92      0.94      4490

   micro avg       0.97      0.97      0.97     18278
   macro avg       0.96      0.95      0.96     18278
weighted avg       0.97      0.97      0.97     18278

The number of values in a test_label:
18278
Accuracy: 0.927617901302
              precision    recall  f1-score   support

           0       0.94      0.98      0.96     16263
           1       0.75      0.52      0.61      2015

   micro avg       0.93      0.93      0.93     18278
   macro avg       0.85      0.75      0.79     18278
weighted avg       0.92      0.93      0.92     18278

0.936709111866
all_predictions LIST
[array([0, 0, 0, ..., 0, 0, 0]), array([0, 1, 0, ..., 0, 0, 0]), array([0, 1, 0, ..., 0, 0, 0]), array([0, 1, 0, ..., 0, 0, 0]), array([1, 0, 1, ..., 0, 0, 0]), array([1, 0, 0, ..., 0, 0, 0]), array([1, 0, 0, ..., 0, 0, 0]), array([1, 0, 0, 

[array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 1, 0, ..., 0, 0, 0]),
 array([0, 1, 0, ..., 0, 0, 0]),
 array([0, 1, 0, ..., 0, 0, 0]),
 array([1, 0, 1, ..., 0, 0, 0]),
 array([1, 0, 0, ..., 0, 0, 0]),
 array([1, 0, 0, ..., 0, 0, 0]),
 array([1, 0, 0, ..., 0, 0, 0]),
 array([1, 0, 1, ..., 0, 0, 0]),
 array([1, 0, 0, ..., 0, 0, 0]),
 array([1, 0, 0, ..., 0, 0, 0]),
 array([1, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 1]),
 array([0, 0, 0, ..., 0, 0, 1]),
 array([0, 0, 0, ..., 0, 0, 1]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 1, 1, 1]),
 array([0, 0, 0, ..., 1, 1, 1]),
 array([0, 0, 0, ..., 1, 1, 1]),
 array([0, 0, 0, ..., 0, 0, 0])]

In [45]:
#To create a dataframe from the predictions
df = pd.DataFrame(all_predictions, index = ['gk', 'ls', 'st', 'rs', 'lw', 'lf', 'cf', 'rf', 'rw', 'lam', 'cam', 'ram', 'lm', 'lcm', 'cm', 'rcm', 'rm', 'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb'])
addT = df.T

In [49]:
#Pass the final Data Frame of labels, the model name, and the position 
#Positions you can pick from to classify what players can substitue for that position
#p = ['gk', 'ls', 'st', 'rs', 'lw', 'lf', 'cf', 'rf', 'rw', 'lam', 'cam', 'ram', 'lm', 'lcm', 'cm', 'rcm', 'rm', 'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb']
apply_postprocessing(addT, "LogistRegressionEnsemble", 'lw')

Number of classes:
18278
TEST DATA READ
Neymar da Silva Santos Junior can substitute for the position lw, Left winger position, which is a(n) attacker position. 

Eden Hazard can substitute for the position lw, Left winger position, which is a(n) attacker position. 

Mohamed  Salah Ghaly can substitute for the position lw, Left winger position, which is a(n) attacker position. 

Kylian Mbappé can substitute for the position lw, Left winger position, which is a(n) attacker position. 

Antoine Griezmann can substitute for the position lw, Left winger position, which is a(n) attacker position. 

Paulo Bruno Exequiel Dybala can substitute for the position lw, Left winger position, which is a(n) attacker position. 

Raheem Sterling can substitute for the position lw, Left winger position, which is a(n) attacker position. 

Marco Reus can substitute for the position lw, Left winger position, which is a(n) attacker position. 

Sadio Mané can substitute for the position lw, Left winger positio


Harrison Manzala can substitute for the position lw, Left winger position, which is a(n) attacker position. 

Juan Ignacio Cavallaro can substitute for the position lw, Left winger position, which is a(n) attacker position. 

Edgar Mauricio Gómez Sánchez can substitute for the position lw, Left winger position, which is a(n) attacker position. 

Yairo Yesid Moreno Berrío can substitute for the position lw, Left winger position, which is a(n) attacker position. 

Dimitrios Kolovos can substitute for the position lw, Left winger position, which is a(n) attacker position. 

Tony Mauricio can substitute for the position lw, Left winger position, which is a(n) attacker position. 

Quentin Cornette can substitute for the position lw, Left winger position, which is a(n) attacker position. 

Jesús Jiménez Núñez can substitute for the position lw, Left winger position, which is a(n) attacker position. 

Filip Holender can substitute for the position lw, Left winger position, which is a(n) atta

Nicolás Hidalgo García can substitute for the position lw, Left winger position, which is a(n) attacker position. 

Dennis  Mast can substitute for the position lw, Left winger position, which is a(n) attacker position. 

永井 龍 can substitute for the position lw, Left winger position, which is a(n) attacker position. 

Adrian Dumitru Popa can substitute for the position lw, Left winger position, which is a(n) attacker position. 

Chris Erskine can substitute for the position lw, Left winger position, which is a(n) attacker position. 

Sergio Esteban Romero Méndez can substitute for the position lw, Left winger position, which is a(n) attacker position. 

Darwin Guillermo López Tobías can substitute for the position lw, Left winger position, which is a(n) attacker position. 

Misael Dávila can substitute for the position lw, Left winger position, which is a(n) attacker position. 

안용우 安庸佑 can substitute for the position lw, Left winger position, which is a(n) attacker position. 

谢鹏飞 can


Abdulaziz Al Aryani can substitute for the position lw, Left winger position, which is a(n) attacker position. 

주현호 朱贤虎 can substitute for the position lw, Left winger position, which is a(n) attacker position. 

Moses Ebiye can substitute for the position lw, Left winger position, which is a(n) attacker position. 

Cory Galvin can substitute for the position lw, Left winger position, which is a(n) attacker position. 

Daniel Kelly can substitute for the position lw, Left winger position, which is a(n) attacker position. 

Dennis Salanovic can substitute for the position lw, Left winger position, which is a(n) attacker position. 

Daire O'Connor can substitute for the position lw, Left winger position, which is a(n) attacker position. 

Filip Lesniak can substitute for the position lw, Left winger position, which is a(n) attacker position. 

Kristoffer Ødemarksbakken can substitute for the position lw, Left winger position, which is a(n) attacker position. 

Dylan Chambost can substi

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ipykernel_launcher.py:100: FutureWarning: get_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead




The entire roster of players who can be swapped for the Left winger position in order of best overall performance to least based on the LogistRegressionEnsembleare:
Neymar da Silva Santos Junior
Eden Hazard
Mohamed  Salah Ghaly
Kylian Mbappé
Antoine Griezmann
Sadio Mané
Raheem Sterling
Paulo Bruno Exequiel Dybala
Marco Reus
Lorenzo Insigne
Dries Mertens
손흥민 孙兴慜
Ángel Fabián Di María Hernández
Leroy Sané
Philippe Coutinho Correia
Alexandre Lacazette
Gareth Frank Bale
Hakim Ziyech
Alejandro Darío Gómez
Iago Aspas Juncal
Riyad Mahrez
Jadon Sancho
Sergio Canales Madrazo
Kai Havertz
Nabil Fekir
José María Callejón Bueno
Ivan Perišić
Serge Gnabry
Ousmane Dembélé
Felipe  Anderson Pereira Gomes
Julian Brandt
Kingsley Coman
Memphis Depay
Douglas Costa de Souza
Edin Višća
Gonçalo Manuel Ganchinho Guedes
Anthony Martial
Florian Thauvin
Marco Asensio Willemsen
Marcus Rashford
Yannick Ferreira Carrasco
Lucas Rodrigues M. Silva
Carlos Alberto Vela Garrido
Thomas Lemar
Pablo Sarabia García
Julian D

István Fülöp
Burak Çalık
Jean Paul Jesús Pineda Cortés
Manfred Fischer
Mauricio José Yedro
Jacob Brown
Dylan Seys
Robinho Barbosa de Lisboa
Jamie Devitt
Arturo Molina Tornero
Bogdan Mladenovic
Thibaut  Vion
Nicolas Rajsel
Gevaro Nepomuceno
Anthony Forde
Tyrell Matthew Benjamin Rusike
Marc Andre Schmerböck
Ruster Santos D'Ajuda
Bart van Hintum
Mauro Da Luz
Leonardo da Silva Lopes
Iker Guarrotxena Vallejo
Mustapha Bundu
Joao Rodríguez
Steve Lawson
Rafik Guitane
José Uilton Silva de Jesus
Omar Arellano Riverón
Bård Finne
Cyrille Bayala
Luis Díaz
Matthias Verreth
Abdoulaye Sané
Bright Osayi-Samuel
Dennis Jastrzembski
조영욱 Young Wook Cho
Daniel Gustafsson
Andrei Ciobanu
Taxiarchis Fountas
Moussa Jailani Njie
Aïssa Laïdouni
Jason Flores Abrigo
Alessandro Capello
Mihai Căpățînă
Giuseppe Panico
Riku Riski
Sebastián Galani
Herolind Shala
Erick de Arruda Serafim
Mirko Carretta
Joe Ward
Mihai Răduț
Mohamed Gouaida
Anas Tahiri
Luca Orellano
Darren Maatsen
Mickaël Mathieu Latour
Enzo Lombardo
George

Michał Trąbka
김지현 Ji Hyun Kim
Ali Al Hassan
吴少聪
Ernesto Carratala Jimenez
Fahad Al Rashidi
季骁宣
Pacifique Niyongabire
杨一虎
Mario Shabow
Aboubacar Konte
Sam Nombe
Alex Bradley
Jason Law
Daniel Stynes
Meinhard Olsen
Venancio junior Osman de menezes
樋口 雄太
Tony McNamee
Tommy Pawlson
Dion Sanderson
Silas Schwarz
Yahya Khormi
Mark Timlin
Agustín Obando
Joachim Olufsen
Jamie Semple
Hussain Al Eissa
Justin Roth
Maher Al Mutairi
Hasan Huseyin Duman
Mathieu Troonbeeckx
Oliver Klitten
Lorenz Grabovac
Jesús Garza
Laorent Shabani
Pedro Campos
Ema Twumasi
Brayan Palmezano
Andre Hasanally
John Russell
Mohsen Abdullah
Neil Farrugia
Mikey Place
Henrik Bellman
Liam Kerrigan
Steven Alzate
Rahmat Akbari
Albie Morgan
Gaétan Bosiers
Brayan Moreno
Tyler Hamilton
Azad Toptik
Pavle Vagic
Jonas Meiser
William Fitzgerald
Faraj Al Ghashayan
명준재 Joon Jae Myeong
Alex Addai
Raffaele Cretaro
杨万顺
Jon Gallagher
Ryan Watson
Paul Costea
Michael Fernandes
Ibrahim Karamoko
Innes Cameron
Birkan Kirdar
Josh Koroma
Alexander Co